from datetime import datetime, timedelta
from typing import Dict, Any


class FollowUpAgent:
    """
    Follow-Up Agent

    Responsibilities:
    - Schedule follow-ups
    - Track patient recovery
    - Generate reminder records
    - Monitor follow-up status
    """

    def __init__(self):
        self.agent_name = "Follow-Up Agent"

    def schedule_followup(
        self,
        patient_context: Dict[str, Any]
    ) -> Dict[str, Any]:

        patient_name = patient_context.get(
            "patient_name",
            "Unknown Patient"
        )

        risk_level = patient_context.get(
            "risk_level",
            "Medium"
        )

        followup_days = {
            "Critical": 3,
            "High": 7,
            "Medium": 14,
            "Low": 30
        }

        days = followup_days.get(
            risk_level,
            14
        )

        followup_date = (
            datetime.now() +
            timedelta(days=days)
        )

        reminder_message = f"""
📋 FOLLOW-UP SCHEDULED

Patient:
{patient_name}

Risk Level:
{risk_level}

Next Follow-Up:
{followup_date.strftime('%Y-%m-%d')}

Status:
Pending

Generated By:
VitalFlow Follow-Up Agent
        """.strip()

        followup_record = {
            "status": "scheduled",
            "agent": self.agent_name,
            "patient": patient_name,
            "risk_level": risk_level,
            "followup_date": followup_date.strftime(
                "%Y-%m-%d"
            ),
            "timestamp": datetime.utcnow().isoformat(),
            "message": reminder_message
        }

        print("\n========================")
        print("FOLLOW-UP CREATED")
        print("========================")
        print(reminder_message)
        print("========================\n")

        return followup_record


if __name__ == "__main__":

    sample_patient_context = {
        "patient_name": "Rahul Sharma",
        "risk_level": "Critical"
    }

    agent = FollowUpAgent()

    result = agent.schedule_followup(
        sample_patient_context
    )

    print(result)