from datetime import datetime
from typing import Dict, Any


class NotificationAgent:
    """
    Notification Agent

    Responsibilities:
    - Generate doctor alerts
    - Generate notification messages
    - Create structured summaries
    - Return notification payloads
    """

    def __init__(self):
        self.agent_name = "Notification Agent"

    def generate_alert(self, patient_context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generates a structured doctor alert
        """

        patient_name = patient_context.get("patient_name", "Unknown Patient")
        risk_level = patient_context.get("risk_level", "Unknown")
        emergency_score = patient_context.get("emergency_score", 0)
        doctor = patient_context.get("assigned_doctor", "Unassigned")
        concern = patient_context.get(
            "possible_concern",
            "Further review required"
        )

        message = f"""
🚨 CRITICAL REPORT ALERT

Patient: {patient_name}
Assigned Doctor: {doctor}

Risk Level: {risk_level}
Emergency Score: {emergency_score}%

Possible Concern:
{concern}

Action Required:
Please review immediately.

Generated By:
VitalFlow Notification Agent
        """.strip()

        return {
            "status": "success",
            "agent": self.agent_name,
            "timestamp": datetime.utcnow().isoformat(),
            "doctor": doctor,
            "message": message
        }

    def send_notification(self, patient_context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Main notification workflow
        """

        alert = self.generate_alert(patient_context)

        # Future integrations:
        # Telegram
        # WhatsApp
        # Email

        print("\n========================")
        print("NOTIFICATION GENERATED")
        print("========================")
        print(alert["message"])
        print("========================\n")

        return alert


if __name__ == "__main__":

    sample_patient_context = {
        "patient_name": "Rahul Sharma",
        "risk_level": "Critical",
        "emergency_score": 94,
        "assigned_doctor": "Dr. Mehta",
        "possible_concern": "Potential cardiac event"
    }

    agent = NotificationAgent()

    result = agent.send_notification(
        sample_patient_context
    )

    print(result)