import {
  Report,
  ReportDetail,
  ComplianceLog,
  FollowUp,
  DashboardStats,
  AgentStatusInfo,
} from './types'

// ─── Mock Data ────────────────────────────────────────────────────────────────

export const mockStats: DashboardStats = {
  total_today: 34,
  critical_count: 7,
  pending_review: 12,
  escalations_active: 3,
}

export const mockAgentStatus: AgentStatusInfo[] = [
  { agent_name: 'Report Intake Agent', status: 'completed', last_run: new Date(Date.now() - 2 * 60000).toISOString() },
  { agent_name: 'Medical Analysis Agent', status: 'completed', last_run: new Date(Date.now() - 4 * 60000).toISOString() },
  { agent_name: 'Patient History Agent', status: 'completed', last_run: new Date(Date.now() - 5 * 60000).toISOString() },
  { agent_name: 'Risk Prediction Agent', status: 'running', last_run: new Date(Date.now() - 1 * 60000).toISOString() },
  { agent_name: 'Emergency Classifier Agent', status: 'completed', last_run: new Date(Date.now() - 3 * 60000).toISOString() },
  { agent_name: 'Explainability Agent', status: 'completed', last_run: new Date(Date.now() - 3.5 * 60000).toISOString() },
  { agent_name: 'Doctor Routing Agent', status: 'running', last_run: new Date(Date.now() - 0.5 * 60000).toISOString() },
  { agent_name: 'Notification Agent', status: 'completed', last_run: new Date(Date.now() - 6 * 60000).toISOString() },
  { agent_name: 'Escalation Agent', status: 'failed', last_run: new Date(Date.now() - 8 * 60000).toISOString() },
  { agent_name: 'Follow-Up Scheduler Agent', status: 'completed', last_run: new Date(Date.now() - 10 * 60000).toISOString() },
]

export const mockReports: Report[] = [
  {
    report_id: 'RPT-001',
    patient_name: 'Aditya Sharma',
    patient_age: 62,
    patient_id: 'PID-1042',
    report_type: 'Blood Test',
    uploaded_at: new Date(Date.now() - 12 * 60000).toISOString(),
    urgency: 'Critical',
    risk_score: 92,
    emergency_prediction_score: 88,
    assigned_doctor: 'Dr. Priya Nair',
    status: 'Pending Review',
    referring_doctor: 'Dr. Rahul Mehta',
  },
  {
    report_id: 'RPT-002',
    patient_name: 'Meena Verma',
    patient_age: 45,
    patient_id: 'PID-2031',
    report_type: 'ECG',
    uploaded_at: new Date(Date.now() - 25 * 60000).toISOString(),
    urgency: 'Critical',
    risk_score: 85,
    emergency_prediction_score: 79,
    assigned_doctor: 'Dr. Arjun Kapoor',
    status: 'Escalated',
    referring_doctor: 'Dr. Sunita Rao',
  },
  {
    report_id: 'RPT-003',
    patient_name: 'Raj Kumar',
    patient_age: 38,
    patient_id: 'PID-3087',
    report_type: 'CT Scan',
    uploaded_at: new Date(Date.now() - 45 * 60000).toISOString(),
    urgency: 'Medium',
    risk_score: 58,
    emergency_prediction_score: 52,
    assigned_doctor: 'Dr. Vikram Singh',
    status: 'Acknowledged',
    referring_doctor: 'Dr. Priya Nair',
  },
  {
    report_id: 'RPT-004',
    patient_name: 'Kavitha Reddy',
    patient_age: 55,
    patient_id: 'PID-4012',
    report_type: 'MRI',
    uploaded_at: new Date(Date.now() - 60 * 60000).toISOString(),
    urgency: 'Medium',
    risk_score: 47,
    emergency_prediction_score: 41,
    assigned_doctor: 'Dr. Sunita Rao',
    status: 'Pending Review',
    referring_doctor: 'Dr. Vikram Singh',
  },
  {
    report_id: 'RPT-005',
    patient_name: 'Suresh Patel',
    patient_age: 72,
    patient_id: 'PID-5023',
    report_type: 'Blood Test',
    uploaded_at: new Date(Date.now() - 90 * 60000).toISOString(),
    urgency: 'Critical',
    risk_score: 78,
    emergency_prediction_score: 74,
    assigned_doctor: 'Dr. Priya Nair',
    status: 'Pending Review',
    referring_doctor: 'Dr. Arjun Kapoor',
  },
  {
    report_id: 'RPT-006',
    patient_name: 'Anjali Iyer',
    patient_age: 29,
    patient_id: 'PID-6044',
    report_type: 'X-Ray',
    uploaded_at: new Date(Date.now() - 110 * 60000).toISOString(),
    urgency: 'Low',
    risk_score: 22,
    emergency_prediction_score: 18,
    assigned_doctor: 'Dr. Rahul Mehta',
    status: 'Acknowledged',
    referring_doctor: 'Dr. Rahul Mehta',
  },
  {
    report_id: 'RPT-007',
    patient_name: 'Mohan Das',
    patient_age: 67,
    patient_id: 'PID-7055',
    report_type: 'Blood Test',
    uploaded_at: new Date(Date.now() - 150 * 60000).toISOString(),
    urgency: 'Medium',
    risk_score: 53,
    emergency_prediction_score: 49,
    assigned_doctor: 'Dr. Vikram Singh',
    status: 'Complete',
    referring_doctor: 'Dr. Sunita Rao',
  },
  {
    report_id: 'RPT-008',
    patient_name: 'Nalini Krishnan',
    patient_age: 41,
    patient_id: 'PID-8066',
    report_type: 'ECG',
    uploaded_at: new Date(Date.now() - 200 * 60000).toISOString(),
    urgency: 'Low',
    risk_score: 15,
    emergency_prediction_score: 12,
    assigned_doctor: 'Dr. Rahul Mehta',
    status: 'Complete',
    referring_doctor: 'Dr. Priya Nair',
  },
]

const mockAgentPipeline = [
  { agent_name: 'Report Intake Agent', action: 'Parsed PDF and extracted structured medical data', timestamp: new Date(Date.now() - 12 * 60000).toISOString(), duration_ms: 420, status: 'completed' as const },
  { agent_name: 'Medical Analysis Agent', action: 'Identified 4 abnormal biomarkers with clinical significance', timestamp: new Date(Date.now() - 11 * 60000).toISOString(), duration_ms: 1850, status: 'completed' as const },
  { agent_name: 'Patient History Agent', action: 'Retrieved 3 prior reports; found consistent elevation pattern', timestamp: new Date(Date.now() - 10 * 60000).toISOString(), duration_ms: 730, status: 'completed' as const },
  { agent_name: 'Risk Prediction Agent', action: 'Computed risk score 92/100 using ensemble model', timestamp: new Date(Date.now() - 9 * 60000).toISOString(), duration_ms: 2100, status: 'completed' as const },
  { agent_name: 'Emergency Classifier Agent', action: 'Classified as CRITICAL — immediate review required', timestamp: new Date(Date.now() - 8 * 60000).toISOString(), duration_ms: 310, status: 'completed' as const },
  { agent_name: 'Explainability Agent', action: 'Generated clinical narrative and deviation summary', timestamp: new Date(Date.now() - 7 * 60000).toISOString(), duration_ms: 980, status: 'completed' as const },
  { agent_name: 'Doctor Routing Agent', action: 'Assigned to Dr. Priya Nair (Cardiology)', timestamp: new Date(Date.now() - 6 * 60000).toISOString(), duration_ms: 150, status: 'completed' as const },
  { agent_name: 'Notification Agent', action: 'Sent Telegram alert + email to Dr. Priya Nair', timestamp: new Date(Date.now() - 5 * 60000).toISOString(), duration_ms: 870, status: 'completed' as const },
  { agent_name: 'Escalation Agent', action: 'Scheduled 5-minute escalation timer — no acknowledgement received', timestamp: new Date(Date.now() - 4 * 60000).toISOString(), duration_ms: 200, status: 'completed' as const },
  { agent_name: 'Follow-Up Scheduler Agent', action: 'Scheduled follow-up in 48 hours', timestamp: new Date(Date.now() - 3 * 60000).toISOString(), duration_ms: 340, status: 'completed' as const },
]

export const mockReportDetail: ReportDetail = {
  ...mockReports[0],
  abnormal_flags: [
    { test_name: 'Troponin I', value: 2.4, unit: 'ng/mL', reference_range: '0.0–0.04', deviation_percent: 5900, risk_level: 'Critical', possible_concern: 'Acute Myocardial Infarction', suggested_action: 'Immediate cardiology review and ECG' },
    { test_name: 'CK-MB', value: 48, unit: 'U/L', reference_range: '0–25', deviation_percent: 92, risk_level: 'High', possible_concern: 'Cardiac muscle damage', suggested_action: 'Serial enzyme monitoring' },
    { test_name: 'BNP', value: 890, unit: 'pg/mL', reference_range: '<100', deviation_percent: 790, risk_level: 'Critical', possible_concern: 'Heart failure', suggested_action: 'Echocardiogram and diuretic assessment' },
    { test_name: 'D-Dimer', value: 3.2, unit: 'µg/mL', reference_range: '<0.5', deviation_percent: 540, risk_level: 'High', possible_concern: 'Pulmonary embolism risk', suggested_action: 'CT pulmonary angiography' },
  ],
  explainability_text: 'This report was scored CRITICAL (92/100) due to severely elevated Troponin I (5900% above normal), indicating acute myocardial injury. Combined with elevated BNP suggesting concurrent heart failure and elevated D-Dimer raising PE risk, this patient requires immediate cardiology intervention. Historical data shows 2 prior elevated troponin readings in the last 6 months, confirming a deteriorating cardiac pattern.',
  patient_history_summary: 'Patient has 3 prior blood test reports on file. Troponin I has been trending upward over 6 months. Known history of hypertension (2 years) and Type 2 Diabetes (5 years). Previous ECG (4 months ago) showed mild ST-segment changes. No prior cardiac interventions. Currently on Metformin and Amlodipine.',
  routing_reason: 'Assigned to Dr. Priya Nair (Senior Cardiologist) based on critical cardiac biomarker pattern. Cardiology specialty match score: 0.97. Dr. Nair is on-duty and has capacity.',
  agent_pipeline: mockAgentPipeline,
  pipeline_completed_at: new Date(Date.now() - 3 * 60000).toISOString(),
}

export const mockComplianceLogs: ComplianceLog[] = [
  {
    report_id: 'RPT-001',
    patient_name: 'Aditya Sharma',
    uploaded_at: new Date(Date.now() - 12 * 60000).toISOString(),
    pipeline_completed_at: new Date(Date.now() - 9 * 60000).toISOString(),
    total_time_seconds: 187,
    sla_status: 'Met',
    agent_steps: mockAgentPipeline,
  },
  {
    report_id: 'RPT-002',
    patient_name: 'Meena Verma',
    uploaded_at: new Date(Date.now() - 25 * 60000).toISOString(),
    pipeline_completed_at: new Date(Date.now() - 18 * 60000).toISOString(),
    total_time_seconds: 412,
    sla_status: 'Breached',
    agent_steps: mockAgentPipeline.map(s => ({ ...s })),
  },
  {
    report_id: 'RPT-003',
    patient_name: 'Raj Kumar',
    uploaded_at: new Date(Date.now() - 45 * 60000).toISOString(),
    pipeline_completed_at: new Date(Date.now() - 42 * 60000).toISOString(),
    total_time_seconds: 164,
    sla_status: 'Met',
    agent_steps: mockAgentPipeline.map(s => ({ ...s })),
  },
  {
    report_id: 'RPT-004',
    patient_name: 'Kavitha Reddy',
    uploaded_at: new Date(Date.now() - 60 * 60000).toISOString(),
    pipeline_completed_at: new Date(Date.now() - 56 * 60000).toISOString(),
    total_time_seconds: 231,
    sla_status: 'Met',
    agent_steps: mockAgentPipeline.map(s => ({ ...s })),
  },
  {
    report_id: 'RPT-005',
    patient_name: 'Suresh Patel',
    uploaded_at: new Date(Date.now() - 90 * 60000).toISOString(),
    pipeline_completed_at: new Date(Date.now() - 83 * 60000).toISOString(),
    total_time_seconds: 389,
    sla_status: 'Breached',
    agent_steps: mockAgentPipeline.map(s => ({ ...s })),
  },
]

export const mockFollowUps: FollowUp[] = [
  { followup_id: 'FU-001', patient_name: 'Aditya Sharma', doctor_name: 'Dr. Priya Nair', report_type: 'Blood Test', followup_date: new Date(Date.now() + 48 * 3600000).toISOString(), reminder_sent: true, status: 'Scheduled' },
  { followup_id: 'FU-002', patient_name: 'Meena Verma', doctor_name: 'Dr. Arjun Kapoor', report_type: 'ECG', followup_date: new Date(Date.now() + 24 * 3600000).toISOString(), reminder_sent: false, status: 'Scheduled' },
  { followup_id: 'FU-003', patient_name: 'Raj Kumar', doctor_name: 'Dr. Vikram Singh', report_type: 'CT Scan', followup_date: new Date(Date.now() - 2 * 3600000).toISOString(), reminder_sent: true, status: 'Missed' },
  { followup_id: 'FU-004', patient_name: 'Kavitha Reddy', doctor_name: 'Dr. Sunita Rao', report_type: 'MRI', followup_date: new Date(Date.now() - 5 * 3600000).toISOString(), reminder_sent: true, status: 'Completed' },
  { followup_id: 'FU-005', patient_name: 'Anjali Iyer', doctor_name: 'Dr. Rahul Mehta', report_type: 'X-Ray', followup_date: new Date(Date.now() + 72 * 3600000).toISOString(), reminder_sent: false, status: 'Pending' },
  { followup_id: 'FU-006', patient_name: 'Suresh Patel', doctor_name: 'Dr. Priya Nair', report_type: 'Blood Test', followup_date: new Date(Date.now() + 96 * 3600000).toISOString(), reminder_sent: false, status: 'Scheduled' },
]
